openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /submit:
    post:
      tags:
      - request-controller
      summary: Yeni iş gönder
      description: Bir JSON payload alır ve işleme alır.
      operationId: submit
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestDTO"
        required: true
      responses:
        "202":
          description: İstek kabul edildi
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
  /status/{id}:
    get:
      tags:
      - request-controller
      summary: İşin durumunu getir
      description: ID ile durum sorgusu yapılır.
      operationId: status
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "404":
          description: İstek bulunamadı
          content:
            '*/*':
              schema:
                type: object
        "200":
          description: Durum bulundu
          content:
            '*/*':
              schema:
                type: object
components:
  schemas:
    RequestDTO:
      type: object
      properties:
        payload:
          type: object
          additionalProperties:
            type: object
