version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - internal_net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - internal_net

  postgres:
    image: postgres:15
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_DB: virtual_thread_db
      POSTGRES_USER: vtuser
      POSTGRES_PASSWORD: vtpassword
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal_net

volumes:
  pg_data:

networks:
  internal_net:
    driver: bridge
