version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - internal_net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - internal_net

  postgres:
    image: postgres:15
    container_name: pg_container
    environment:
      POSTGRES_DB: virtual_thread_db
      POSTGRES_USER: vtuser
      POSTGRES_PASSWORD: vtpassword
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal_net

  springboot:
    build: .
    container_name: springboot_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/virtual_thread_db
      SPRING_DATASOURCE_USERNAME: vtuser
      SPRING_DATASOURCE_PASSWORD: vtpassword
    ports:
      - "8080:8080"
    networks:
      - internal_net

  mock-service:
    build:
      context: ./python-mock
    container_name: mock_service
    ports:
      - "5000:5000"
    networks:
      - internal_net

volumes:
  pg_data:

networks:
  internal_net:
    driver: bridge
